language: objective-c

branches:
    only:
        - master

xcode_project: BinarySpec.xcodeproj
xcode_scheme: BinarySpecTests
osx_image: xcode7.1

xcode_sdk:
    - iphonesimulator9.1
    - iphoneos9.1
    - macosx10.11
    - tvos9.0

