language: objective-c

xcode_project: BinarySpec.xcodeproj
xcode_scheme: BinarySpecTests
osx_image: xcode7.3

env:
    - XCODE_SDK=iphonesimulator9.3 TEST_SCHEME=BinarySpecTests
    - XCODE_SDK=appletvsimulator9.2 TEST_SCHEME=BinarySpecTests
    - XCODE_SDK=macosx10.11 TEST_SCHEME=BinarySpecTests_OSX

## Travis doesn't seem to support the real devices yet
#    - XCODE_SDK=iphoneos9.1
#    - XCODE_SDK=appletvos9.0

script:
    - xctool -workspace BinarySpec.xcworkspace -scheme $TEST_SCHEME -sdk $XCODE_SDK build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

