language: objective-c

xcode_project: BinarySpec.xcodeproj
xcode_scheme: BinarySpecTests
osx_image: xcode7.1

env:
    - XCODE_SDK=iphonesimulator9.1
    - XCODE_SDK=macosx10.11
## The AppleTV simulator's XCTest is referring to the wrong library paths :(
#    - XCODE_SDK=appletvsimulator9.0
## Travis doesn't seem to support the real devices yet
#    - XCODE_SDK=iphoneos9.1
#    - XCODE_SDK=appletvos9.0

script:
    - xctool -project BinarySpec.xcodeproj -scheme BinarySpecTests -sdk $XCODE_SDK build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

